id: ans.fhir.fr.tde
canonical: https://interop.esante.gouv.fr/ig/fhir/tde # the last part of canonical and id must be the same
name: TDE # Should be an acronym
title: ANS - Traçabilité des événements
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 2.0.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension



pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        sf1.md:
            title: Vue d'ensemble
    specification_technique_intro.md:
        title: Volume 2 - Détail des transactions
        correspondance_metier.md:
            title: Correspondances métier
        api.md:
            title: Via API REST
        syslog.md:
            title: Via syslog
    change-log.md:
        title: Historique des versions
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: index.html
    Volume 2 - Détail des transactions:
        Introduction: specification_technique_intro.html
        Correspondances métier: correspondance_metier.html
        Via API REST: api.html
        Via syslog: syslog.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: change-log.html
