id: ans.fhir.fr.tde
canonical: https://interop.esante.gouv.fr/ig/fhir/tde # the last part of canonical and id must be the same
name: TDE # Should be an acronym
title: ANS - Traçabilité des événements
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 2.0.0-ballot # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ballot # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

dependencies:
    hl7.fhir.fr.core: 2.1.0

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension



pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
            title: Volume 1 - Etude fonctionnelle
    specifications_technique_intro.md:
        title: Volume 2 - Détail des transactions
        specifications_technique_correspondance_metier.md:
            title: Correspondances métier
        specifications_technique_api.md:
            title: Via API REST
        specifications_technique_syslog.md:
            title: Via syslog
    change-log.md:
        title: Historique des versions
    securite.md:
        title: Sécurité
    downloads.md:
        title: Téléchargements et usages
    normes_standards.md:
        title: Etude norme et standards
    annexe_audit_dicom.md:
        title: Mise en correspondance AuditEvent / DICOM
    glossaire.md:
        title: Glossaire
menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: specifications_fonctionnelles.html
    Volume 2 - Détail des transactions:
        Introduction: specifications_technique_intro.html
        Correspondances métier: specifications_technique_correspondance_metier.html
        Via API REST: specifications_technique_api.html
        Via syslog: specifications_technique_syslog.html
    Volume 3 - Annexes:
        Normes et standards: normes_standards.html
        Glossaire: glossaire.html
        Mise en correspondance AuditEvent / DICOM: annexe_audit_dicom.html
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/

    Ressources de conformité: artifacts.html
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: change-log.html
